mkdir -p OBJ bin src
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/mod_nfseis.F90 > ./src/mod_nfseis.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/mod_nfseis.f90 -o OBJ/mod_nfseis.o
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/mod_para.F90 > ./src/mod_para.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/mod_para.f90 -o OBJ/mod_para.o
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/mod_mpi.F90 > ./src/mod_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/mod_mpi.f90 -o OBJ/mod_mpi.o
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/mod_grid.F90 > ./src/mod_grid.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/mod_grid.f90 -o OBJ/mod_grid.o
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/mod_io.F90 > ./src/mod_io.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/mod_io.f90 -o OBJ/mod_io.o
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/mod_media.F90 > ./src/mod_media.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/mod_media.f90 -o OBJ/mod_media.o
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/mod_macdrp.F90 > ./src/mod_macdrp.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/mod_macdrp.f90 -o OBJ/mod_macdrp.o
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/mod_src.F90 > ./src/mod_src.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/mod_src.f90 -o OBJ/mod_src.o
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/mod_custom.F90 > ./src/mod_custom.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/mod_custom.f90 -o OBJ/mod_custom.o
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/seis3d_grid.F90 > ./src/seis3d_grid.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/seis3d_grid.f90 -o OBJ/seis3d_grid.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/seis3d_grid ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/seis3d_grid.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/seis3d_metric.F90 > ./src/seis3d_metric.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/seis3d_metric.f90 -o OBJ/seis3d_metric.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/seis3d_metric ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/seis3d_metric.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/seis3d_media.F90 > ./src/seis3d_media.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/seis3d_media.f90 -o OBJ/seis3d_media.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/seis3d_media ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/seis3d_media.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DMediaMPI ./srcF/seis3d_media.F90 > ./src/seis3d_media_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/seis3d_media_mpi.f90 -o OBJ/seis3d_media_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/seis3d_media_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/seis3d_media_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/seis3d_source.F90 > ./src/seis3d_source.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/seis3d_source.f90 -o OBJ/seis3d_source.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/seis3d_source ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/seis3d_source.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/seis3d_station.F90 > ./src/seis3d_station.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/seis3d_station.f90 -o OBJ/seis3d_station.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/seis3d_station ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/seis3d_station.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/mod_abs_npml.F90 > ./src/mod_abs_npml.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/mod_abs_npml.f90 -o OBJ/mod_abs_npml.o
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF/seis3d_wave_8op_p3.F90 > ./src/seis3d_wave.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/seis3d_wave.f90 -o OBJ/seis3d_wave.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/seis3d_wave_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/mod_abs_npml.o ./OBJ/seis3d_wave.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF.kernel/SI_ker_pair.F90 > ./src/SI_ker_pair.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_pair.f90 -o OBJ/SI_ker_pair.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_pair ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_pair.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp  -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DKernelMPI ./srcF.kernel/SI_ker_pair.F90 > ./src/SI_ker_pair_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_pair_mpi.f90 -o OBJ/SI_ker_pair_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_pair_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_pair_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF.kernel/SI_ker_sta.F90 > ./src/SI_ker_sta.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_sta.f90 -o OBJ/SI_ker_sta.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_sta ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_sta.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp  -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DKernelMPI ./srcF.kernel/SI_ker_sta.F90 > ./src/SI_ker_sta_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_sta_mpi.f90 -o OBJ/SI_ker_sta_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_sta_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_sta_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF.kernel/SI_ker_sta_rho.F90 > ./src/SI_ker_sta_rho.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_sta_rho.f90 -o OBJ/SI_ker_sta_rho.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_sta_rho ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_sta_rho.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp  -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DKernelMPI ./srcF.kernel/SI_ker_sta_rho.F90 > ./src/SI_ker_sta_rho_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_sta_rho_mpi.f90 -o OBJ/SI_ker_sta_rho_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_sta_rho_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_sta_rho_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF.kernel/SI_ker_sta_lamu.F90 > ./src/SI_ker_sta_lamu.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_sta_lamu.f90 -o OBJ/SI_ker_sta_lamu.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_sta_lamu ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_sta_lamu.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp  -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DKernelMPI ./srcF.kernel/SI_ker_sta_lamu.F90 > ./src/SI_ker_sta_lamu_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_sta_lamu_mpi.f90 -o OBJ/SI_ker_sta_lamu_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_sta_lamu_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_sta_lamu_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF.kernel/SI_ker2info.F90 > ./src/SI_ker2info.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker2info.f90 -o OBJ/SI_ker2info.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker2info ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker2info.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp  -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DKernelInfoMPI ./srcF.kernel/SI_ker2info.F90 > ./src/SI_ker2info_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker2info_mpi.f90 -o OBJ/SI_ker2info_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker2info_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker2info_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF.kernel/SI_ker2assm.F90 > ./src/SI_ker2assm.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker2assm.f90 -o OBJ/SI_ker2assm.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker2assm ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker2assm.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp  -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DKernelAssmMPI ./srcF.kernel/SI_ker2assm.F90 > ./src/SI_ker2assm_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker2assm_mpi.f90 -o OBJ/SI_ker2assm_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker2assm_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker2assm_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF.kernel/SI_ker_lamu2assm.F90 > ./src/SI_ker_lamu2assm.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_lamu2assm.f90 -o OBJ/SI_ker_lamu2assm.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_lamu2assm ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_lamu2assm.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp  -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DKernelAssmMPI ./srcF.kernel/SI_ker_lamu2assm.F90 > ./src/SI_ker_lamu2assm_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_lamu2assm_mpi.f90 -o OBJ/SI_ker_lamu2assm_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_lamu2assm_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_lamu2assm_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF.kernel/SI_ker_kamu2assm.F90 > ./src/SI_ker_kamu2assm.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_kamu2assm.f90 -o OBJ/SI_ker_kamu2assm.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_kamu2assm ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_kamu2assm.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp  -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DKernelAssmMPI ./srcF.kernel/SI_ker_kamu2assm.F90 > ./src/SI_ker_kamu2assm_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_kamu2assm_mpi.f90 -o OBJ/SI_ker_kamu2assm_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_kamu2assm_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_kamu2assm_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF.kernel/SI_ker_lamu2vpvs.F90 > ./src/SI_ker_lamu2vpvs.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_lamu2vpvs.f90 -o OBJ/SI_ker_lamu2vpvs.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_lamu2vpvs ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_lamu2vpvs.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp  -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DKernelMPI ./srcF.kernel/SI_ker_lamu2vpvs.F90 > ./src/SI_ker_lamu2vpvs_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_lamu2vpvs_mpi.f90 -o OBJ/SI_ker_lamu2vpvs_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_lamu2vpvs_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_lamu2vpvs_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF.kernel/SI_ker_lamu2kamu.F90 > ./src/SI_ker_lamu2kamu.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_lamu2kamu.f90 -o OBJ/SI_ker_lamu2kamu.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_lamu2kamu ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_lamu2kamu.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp  -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DKernelMPI ./srcF.kernel/SI_ker_lamu2kamu.F90 > ./src/SI_ker_lamu2kamu_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_lamu2kamu_mpi.f90 -o OBJ/SI_ker_lamu2kamu_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_lamu2kamu_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_lamu2kamu_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  ./srcF.kernel/SI_ker_vpvs2kamu.F90 > ./src/SI_ker_vpvs2kamu.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_vpvs2kamu.f90 -o OBJ/SI_ker_vpvs2kamu.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_vpvs2kamu ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_vpvs2kamu.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
/share/pkg/gcc/4.8.1/bin/cpp  -P -traditional -I./srcF -DSTATIC -DUSEPML -DSrcSmooth -DSrcSurface -DCondFreeTIMG -DCondFreeVLOW  -DKernelMPI ./srcF.kernel/SI_ker_vpvs2kamu.F90 > ./src/SI_ker_vpvs2kamu_mpi.f90
/share/pkg/gcc/4.8.1/bin/gcc -O3 -xW -ftz -align records -unroll1 -ipo -c -module ./OBJ -I/share/pkg/netcdf/4.3.0/include  ./src/SI_ker_vpvs2kamu_mpi.f90 -o OBJ/SI_ker_vpvs2kamu_mpi.o
/share/pkg/gcc/4.8.1/bin/gcc -o bin/SI_ker_vpvs2kamu_mpi ./OBJ/mod_constants.o ./OBJ/mod_math.o ./OBJ/mod_string.o ./OBJ/mod_nfseis.o ./OBJ/mod_para.o ./OBJ/mod_mpi.o ./OBJ/mod_grid.o ./OBJ/mod_io.o ./OBJ/mod_media.o ./OBJ/mod_macdrp.o ./OBJ/mod_src.o ./OBJ/mod_custom.o ./OBJ/SI_ker_vpvs2kamu_mpi.o -ipo -L/share/pkg/netcdf/4.3.0/lib -lnetcdf -Bstatic -static
rm SI_ker_sta.f90 SI_ker_lamu2kamu.f90 SI_ker_sta_lamu.f90 mod_abs_npml.f90 seis3d_media.f90 mod_io.f90 SI_ker_vpvs2kamu.f90 seis3d_source.f90 SI_ker_kamu2assm.f90 mod_nfseis.f90 SI_ker_sta_rho.f90 seis3d_grid.f90 SI_ker_lamu2vpvs.f90 mod_mpi.f90 mod_custom.f90 mod_para.f90 mod_grid.f90 SI_ker_pair.f90 mod_macdrp.f90 SI_ker2info.f90 mod_src.f90 seis3d_metric.f90 seis3d_station.f90 mod_media.f90 SI_ker2assm.f90 SI_ker_lamu2assm.f90
