#******************************************************************************#
#*                         makefile of LSQR solver                            *#
#******************************************************************************#

FC=ifort #
FFLAG=-O3 #-static

all:
	${FC} -o solver_damp_smo_loc_yang ${FFLAG} mod_LSQR.f90 solver_damp_smo_loc_yang.f90

